// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protoc/spacemesher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Postcli struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	GPUIndex string `protobuf:"bytes,2,opt,name=GPUIndex,proto3" json:"GPUIndex,omitempty"` // string File_Index=3;
}

func (x *Postcli) Reset() {
	*x = Postcli{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Postcli) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Postcli) ProtoMessage() {}

func (x *Postcli) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Postcli.ProtoReflect.Descriptor instead.
func (*Postcli) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{0}
}

func (x *Postcli) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Postcli) GetGPUIndex() string {
	if x != nil {
		return x.GPUIndex
	}
	return ""
}

type Plot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId          string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	CommitmentAtxId string `protobuf:"bytes,2,opt,name=CommitmentAtxId,proto3" json:"CommitmentAtxId,omitempty"`
	DataDir         string `protobuf:"bytes,3,opt,name=DataDir,proto3" json:"DataDir,omitempty"`
	FileIndex       string `protobuf:"bytes,4,opt,name=FileIndex,proto3" json:"FileIndex,omitempty"`
	NumUnits        uint32 `protobuf:"varint,5,opt,name=NumUnits,proto3" json:"NumUnits,omitempty"`
	MaxFileSize     uint64 `protobuf:"varint,6,opt,name=MaxFileSize,proto3" json:"MaxFileSize,omitempty"`
	LabelsPerUnit   uint64 `protobuf:"varint,7,opt,name=LabelsPerUnit,proto3" json:"LabelsPerUnit,omitempty"`
	TotalFile       uint32 `protobuf:"varint,8,opt,name=TotalFile,proto3" json:"TotalFile,omitempty"`
}

func (x *Plot) Reset() {
	*x = Plot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plot) ProtoMessage() {}

func (x *Plot) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plot.ProtoReflect.Descriptor instead.
func (*Plot) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{1}
}

func (x *Plot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Plot) GetCommitmentAtxId() string {
	if x != nil {
		return x.CommitmentAtxId
	}
	return ""
}

func (x *Plot) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Plot) GetFileIndex() string {
	if x != nil {
		return x.FileIndex
	}
	return ""
}

func (x *Plot) GetNumUnits() uint32 {
	if x != nil {
		return x.NumUnits
	}
	return 0
}

func (x *Plot) GetMaxFileSize() uint64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *Plot) GetLabelsPerUnit() uint64 {
	if x != nil {
		return x.LabelsPerUnit
	}
	return 0
}

func (x *Plot) GetTotalFile() uint32 {
	if x != nil {
		return x.TotalFile
	}
	return 0
}

type Workers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worker []*Workers_Worker `protobuf:"bytes,1,rep,name=worker,proto3" json:"worker,omitempty"`
}

func (x *Workers) Reset() {
	*x = Workers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workers) ProtoMessage() {}

func (x *Workers) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workers.ProtoReflect.Descriptor instead.
func (*Workers) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{2}
}

func (x *Workers) GetWorker() []*Workers_Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

type Jump2File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File_Index uint32 `protobuf:"varint,1,opt,name=File_Index,json=FileIndex,proto3" json:"File_Index,omitempty"`
}

func (x *Jump2File) Reset() {
	*x = Jump2File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jump2File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jump2File) ProtoMessage() {}

func (x *Jump2File) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jump2File.ProtoReflect.Descriptor instead.
func (*Jump2File) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{3}
}

func (x *Jump2File) GetFile_Index() uint32 {
	if x != nil {
		return x.File_Index
	}
	return 0
}

type StatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{4}
}

type StatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Workers_Worker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string                      `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Providers []*Workers_Worker_Providers `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"`
}

func (x *Workers_Worker) Reset() {
	*x = Workers_Worker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workers_Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workers_Worker) ProtoMessage() {}

func (x *Workers_Worker) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workers_Worker.ProtoReflect.Descriptor instead.
func (*Workers_Worker) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Workers_Worker) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Workers_Worker) GetProviders() []*Workers_Worker_Providers {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Workers_Worker_Providers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider   string `protobuf:"bytes,3,opt,name=Provider,proto3" json:"Provider,omitempty"`
	File_Index string `protobuf:"bytes,4,opt,name=File_Index,json=FileIndex,proto3" json:"File_Index,omitempty"`
	Duration   string `protobuf:"bytes,5,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *Workers_Worker_Providers) Reset() {
	*x = Workers_Worker_Providers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_spacemesher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workers_Worker_Providers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workers_Worker_Providers) ProtoMessage() {}

func (x *Workers_Worker_Providers) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_spacemesher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workers_Worker_Providers.ProtoReflect.Descriptor instead.
func (*Workers_Worker_Providers) Descriptor() ([]byte, []int) {
	return file_protoc_spacemesher_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Workers_Worker_Providers) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Workers_Worker_Providers) GetFile_Index() string {
	if x != nil {
		return x.File_Index
	}
	return ""
}

func (x *Workers_Worker_Providers) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

var File_protoc_spacemesher_proto protoreflect.FileDescriptor

var file_protoc_spacemesher_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x39, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x69, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x47, 0x50, 0x55, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x47, 0x50, 0x55, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x82, 0x02, 0x0a,
	0x04, 0x50, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x78, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x74, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1a, 0x0a, 0x08, 0x4e, 0x75, 0x6d, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x4e, 0x75, 0x6d, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x4d,
	0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x4d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x50, 0x65, 0x72, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x69, 0x6c,
	0x65, 0x22, 0xfa, 0x01, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x2d, 0x0a,
	0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x1a, 0xbf, 0x01, 0x0a,
	0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x62, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x5f, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a,
	0x0a, 0x09, 0x4a, 0x75, 0x6d, 0x70, 0x32, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x5f, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0xc8, 0x01, 0x0a, 0x0b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x72, 0x12,
	0x28, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x63, 0x6c, 0x69, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x6f, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x04, 0x4a,
	0x75, 0x6d, 0x70, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x6d, 0x70,
	0x32, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0b, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x6f, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_spacemesher_proto_rawDescOnce sync.Once
	file_protoc_spacemesher_proto_rawDescData = file_protoc_spacemesher_proto_rawDesc
)

func file_protoc_spacemesher_proto_rawDescGZIP() []byte {
	file_protoc_spacemesher_proto_rawDescOnce.Do(func() {
		file_protoc_spacemesher_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_spacemesher_proto_rawDescData)
	})
	return file_protoc_spacemesher_proto_rawDescData
}

var file_protoc_spacemesher_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protoc_spacemesher_proto_goTypes = []interface{}{
	(*Postcli)(nil),                  // 0: proto.Postcli
	(*Plot)(nil),                     // 1: proto.Plot
	(*Workers)(nil),                  // 2: proto.Workers
	(*Jump2File)(nil),                // 3: proto.Jump2File
	(*StatusReq)(nil),                // 4: proto.StatusReq
	(*StatusResp)(nil),               // 5: proto.StatusResp
	(*Workers_Worker)(nil),           // 6: proto.Workers.Worker
	(*Workers_Worker_Providers)(nil), // 7: proto.Workers.Worker.Providers
}
var file_protoc_spacemesher_proto_depIdxs = []int32{
	6, // 0: proto.Workers.worker:type_name -> proto.Workers.Worker
	7, // 1: proto.Workers.Worker.providers:type_name -> proto.Workers.Worker.Providers
	0, // 2: proto.Spacemesher.GetPlot:input_type -> proto.Postcli
	4, // 3: proto.Spacemesher.GetWorkers:input_type -> proto.StatusReq
	3, // 4: proto.Spacemesher.Jump:input_type -> proto.Jump2File
	4, // 5: proto.Spacemesher.CurrentTask:input_type -> proto.StatusReq
	1, // 6: proto.Spacemesher.GetPlot:output_type -> proto.Plot
	2, // 7: proto.Spacemesher.GetWorkers:output_type -> proto.Workers
	5, // 8: proto.Spacemesher.Jump:output_type -> proto.StatusResp
	1, // 9: proto.Spacemesher.CurrentTask:output_type -> proto.Plot
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protoc_spacemesher_proto_init() }
func file_protoc_spacemesher_proto_init() {
	if File_protoc_spacemesher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_spacemesher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Postcli); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jump2File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workers_Worker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_spacemesher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workers_Worker_Providers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_spacemesher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_spacemesher_proto_goTypes,
		DependencyIndexes: file_protoc_spacemesher_proto_depIdxs,
		MessageInfos:      file_protoc_spacemesher_proto_msgTypes,
	}.Build()
	File_protoc_spacemesher_proto = out.File
	file_protoc_spacemesher_proto_rawDesc = nil
	file_protoc_spacemesher_proto_goTypes = nil
	file_protoc_spacemesher_proto_depIdxs = nil
}
